---
title: "Sara_Herrera_Q15"
author: "Sara Herrera (PID:A59011948)"
date: "7/13/2022"
output:
  pdf_document: default
  html_document: default
---

# Name: Sara Herrera de la Mata
# PID: A59011948

# Covid-19 Variants in California

```{r}
# Calling the libraries that will be used to generate the plot
library(ggplot2)
library(lubridate)
library(dplyr)
```

```{r}
# To read the .csv file downloaded from the California Health and Human Services (CHHS) open data site
data <- read.csv("covid19_variants.csv")
```

```{r}
# To remove the rows that contain "variant_name" = "Other", "Total" (as they're not included in the plot)
# To change the date values from "character" to "date" format
clean.data <- data %>% filter(!variant_name %in% c('Other', 'Total')) %>% mutate(date = as.Date(date))
```

```{r}
# Assigning variables
Percentage <- clean.data$percentage
Date <- clean.data$date
Variant <- clean.data$variant_name
```

```{r}
# Making the plot
plot <- ggplot(data = clean.data, aes(x=Date, y=Percentage, color=Variant)) +
  # Select the data frame, x and y axis variables, and the variable by which the data will be colored by
  geom_line(aes(group=Variant)) +
  # To make a line chart, where every line will be a category of the "Variant" column, meaning a different Covid-19 variant
  theme_bw() +
  # Specifies the theme used for the plot: in this case a white background and thin grey grid lines
  scale_x_date(date_breaks = "1 month", date_labels =  "%b %Y") +
  # Specifies how the dates in the x-axis will be represented, separated by 1 month gaps, and with the label month (in letters abbreviated) and year
  theme(axis.text.x=element_text(angle=60, hjust=1)) +
  # Specifies that the label for the dates in the x-axis is angled
  labs(title = "Covid-19 Variants in California", x = NULL, color = NULL, caption = "Data Source: <https://www.cdph.ca.gov/>") +
  # To label the title of the plot, remove the x-axis label to only keep the dates, remove the label of the variants to only keep the name of each variant next to each associated color, and to add a caption at the bottom of the plot
  ylab("Percentage of sequenced specimens") # To add a y-axis label 
plot
```
